proxies:
- name: MasZulkarnain1thn
  type: trojan
  server: 172.67.5.14
  port: 443
  password: e6531ad5-c788-4feb-8bf4-d67b57df9ed0
  udp: true
  sni: syaefudinmtc.store
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/whatever/trojan-ws"
    headers:
      Host: syaefudinmtc.store
