proxies:
- name: Zulkarnain-GitHub
  type: trojan
  server: quiz.int.vidio.com
  port: 443
  password: 912b78ee-0137-4403-8f6b-8bae2455805f
  sni: id-rajasa.rmatstore.vip
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan"
    headers:
      Host: id-rajasa.rmatstore.vip

- name: Chungleo-GitHub
  type: trojan
  server: quiz.int.vidio.com
  port: 443
  password: 9f74384b-ed7a-4072-8f2e-c0f04a327b11
  udp: true
  sni: id-dwb.wc-webkuy.web.id
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan"
    headers:
      Host: id-dwb.wc-webkuy.web.id
