proxies:
- name: Zulkarnain-GitHub
  type: trojan
  server: 172.67.5.14
  port: 443
  password: 18314307-dae6-4eaf-811d-12ab12143bdc
  udp: true
  sni: vamelsstr.syaefudinmtc.my.id
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan-ws"
    headers:
      Host: vamelsstr.syaefudinmtc.my.id
- name: Chungleo-GitHub
  type: trojan
  server: 172.67.5.14
  port: 443
  password: 2fb468d3-4e8c-48a5-94a8-6ed31da9509f
  udp: true
  sni: fatir.syaefudinmtc.my.id
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/whatever/trojan-ws"
    headers:
      Host: fatir.syaefudinmtc.my.id
