proxies:
- name: Zulkarnain-GitHub
  type: trojan
  server: 104.17.3.81
  port: 443
  password: b25ecb97-8584-45cd-bf6b-285cadd69788
  sni: id-hz2.wc-webkuy.web.id
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan"
    headers:
      Host: id-hz2.wc-webkuy.web.id

- name: Chungleo-GitHub
  type: trojan
  server: quiz.int.vidio.com
  port: 443
  password: 9f74384b-ed7a-4072-8f2e-c0f04a327b11
  udp: true
  sni: id-dwb.wc-webkuy.web.id
  skip-cert-verify: true
  network: ws
  ws-opts:
    path: "/trojan"
    headers:
      Host: id-dwb.wc-webkuy.web.id
